Release of 2018-01-24 :
Bug correction:

1 - When selection of a circle and button  "Align View to... "
Traceback (most recent call last):
File "C:\Users\Mario\AppData\Roaming\FreeCAD\Mod\WorkFeature\WorkFeature
\WF_2015.py", line 10702, in view_align
m_Vertex2 = SubObject.Vertexes[1]
IndexError: list index out of range

Correction done !

2 - 3D Text feature of the WF WB when I came across it. Unfortunately
I did not succeed in finding any surface which did not cause the error
message " Non Planar Surface !".

Issue with location of Font file : correction done !

Modification:
into "Point 1/3" TAB :
	Projected Point(s):

Add functions of annotation  "Macro_BoundingBox_Tracing" (from Mario)
into Bounding Box buttons.
To activate this option, toggle "Info" check box.

Add functions of creation of a Voume in addition to rectangles
into Bounding Box buttons.
To activate this option, toggle "Vol" check box.